import {
  AllInbox,
  BackHand,
  Badge,
  Business,
  Campaign,
  Category,
  Group,
  History,
  LocalOffer,
  Person,
  ReceiptLong,
  RotateRight,
  Settings,
  ShoppingCart,
  Store,
  Work,
} from "@mui/icons-material";
import { ElementType } from "react";

export default {
  "chart-pie": Store,
  business: Business,
  person: Person,
  badge: Badge,
  product: Work,
  stock: AllInbox,
  history: History,
  store: Store,
  category: Category,
  cashier: ShoppingCart,
  borrows: BackHand,
  purchase: ReceiptLong,
  account: Settings,
  overstocks: RotateRight,
  group: Group,
  employee: Badge,
  promotion: LocalOffer,
  broadcast: Campaign,
} as Record<string, ElementType>;
